name: Deploy to CloudPanel VPS

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      
              # 1. Install pnpm on the GitHub Runner
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.2.2  # Or your preferred version

      # 2. Setup Node.js with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'pnpm'

      # 3. Install & Build
      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      # 4. Deploy
      - name: Deploy files via Rsync
        uses: burnett01/rsync-deployments@v9
        with:
          switches: -rlptDvz --no-perms
          path: ./dist/
          remote_path: /home/ezerway-financial-news/htdocs/financial-news.ezerway.com/public
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}